name: Electron-windows

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      TAG: main
      VERSION_NUMBER: 0.10.${{ github.run_number }}

    steps:
      - name: Checkout code - from local github repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Read version from version.json
        shell: bash
        id: read_version
        run: |
          VERSION_NUMBER=$(node -pe "JSON.parse(require('fs').readFileSync('version.json', 'utf8')).VERSION")
          echo "VERSION_NUMBER=${VERSION_NUMBER}" >> $GITHUB_ENV
          echo "Version set to: ${VERSION_NUMBER}"

      - name: Run Git Bash commands - for debugging
        shell: bash
        run: |
          echo "Current directory:"
          pwd
          echo "Git version:"
          git --version
          echo "Listing files:"
          ls -la

      # - name: Clone Repo - used when code is hosted on Azure DevOps
      #   run: >-
      #     git clone --depth 1 --branch v${{ env.VERSION_NUMBER }} https://idville:${{ secrets.IDV_PAT }}@dev.azure.com/idville/IDMx/_git/maia
      #   continue-on-error: false

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10        

      - name: Install dependencies
        run: |
          corepack enable
          yarn install
        working-directory: ./maia/maia-ps-node

      # - name: Bump version
      #   run: npm version patch -m "Bump version to %s" # Use 'major', 'minor', or 'patch' as needed
      #   working-directory: ./maia/maia-ps-electron
      #   continue-on-error: false

      # - name: Update version in electron's package.json
      #   run: |
      #     bash ./update_version.sh ${VERSION_NUMBER}
      #   working-directory: ./maia/maia-ps-electron
      #   continue-on-error: false

      # - name: Update version in ps-node's package.json
      #   run: |
      #     bash ./update_version.sh ${VERSION_NUMBER}
      #   working-directory: ./maia/maia-ps-node
      #   continue-on-error: false

      # - name: Update version in ps-node's package.json
      #   run: |
      #     bash ./update_release-name.sh ${VERSION_NUMBER}-win
      #   working-directory: ./maia/maia-ps-node
      #   continue-on-error: false
        
      # Build maia-ps-node -- gets embedded into electron app (working off tagged code version)
      - name: Build maia-ps-node for WIN
        run: |
          yarn binary:win
        working-directory: ./maia/maia-ps-node

      - name: Install dependencies
        run: |
          pnpm install
        working-directory: ./maia/maia-ps-electron

      # Set up environment variables for signing and notarization
      - name: Set environment variables
        run: |
          echo "AZURE_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "AZURE_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "AZURE_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
          echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV
        working-directory: ./maia/maia-ps-electron

      - name: Set environment variables
        run: |
          echo $AZURE_TENANT_ID
        working-directory: ./maia/maia-ps-electron

      - name: Run Git Bash commands
        shell: bash
        run: |
          echo "Current directory:"
          pwd
          echo "Git version:"
          git --version
          echo "Listing files:"
          ls -la
        working-directory: ./maia/maia-ps-electron

      # Build and sign -- signing not working yet
      - name: Build, sign, and notarize
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}    
          NODE_ENV: production
        run: |
          pnpm build:win
        working-directory: ./maia/maia-ps-electron

      # - name: Commit version bump in maia-ps-node main.ts
      #   run: |
      #     git config --global user.name "github-actions[bot]"
      #     git config --global user.email "github-actions[bot]@users.noreply.github.com"
      #     git add .
      #     git commit -m "Bump version"
      #     git push origin
      #   working-directory: ./maia
      #   continue-on-error: false


